[package]
name = "image_importer"
version = "1.1.0"
authors = ["Aggrathon <antonbjo@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.3"
lazy_static = "1.4"
chrono = "0.4"
walkdir = "2.2"
clap = "~2.33"
