[package]
name = "image_importer"
version = "0.1.0"
authors = ["Aggrathon <antonbjo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3"
lazy_static = "1.4"
chrono = "0.4"
walkdir = "2.2"
